In [20]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [21]:
a=numpy.zeros(shape=(10))
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2、创建一个元素为从10到49的ndarray对象

In [7]:
numpy.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

如何创建一个3*3的二维数组，值全为True（真）？

In [8]:
numpy.full(shape=(3,3),fill_value=True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

如何创建一个3×3的二维数组，值域为0到8？

In [10]:
numpy.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

如何从数组np.array([1, 2, 0, 0, 4, 0])中找出非0元素的位置索引？

In [15]:
a=numpy.array([1, 2, 0, 0, 4, 0])
numpy.where(a==0)

(array([2, 3, 5], dtype=int64),)

如何从数组
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
中提取所有的奇数？

In [19]:
a=numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# a 是一个数组的名字  也可以作为每一个元素进行逻辑操作
a[a%2!=0]
# b=numpy.where(a%2!=0)
# for i in b:
#     print(a[i])

array([1, 3, 5, 7, 9])

如何将数组
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
中的所有奇数替换为-1？

In [37]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[a%2!=0]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

如何将数组
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
中的所有奇数替换为-1，而不改变原数组？

In [40]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# where 和sql中的if相似  if(a%2!=0,-1,a) 只是查询的时候对查询的结果赋值，不改变原数组
b=numpy.where(a%2!=0,-1,a)
print(a,b)

[0 1 2 3 4 5 6 7 8 9] [ 0 -1  2 -1  4 -1  6 -1  8 -1]


如何将一维数组
np.arange(10)
转换为2行的二维数组？

In [44]:
a=np.arange(10)
np.reshape(a,newshape=(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

如何将数组
a = np.arange(10).reshape(2,-1)
和数组
b = np.repeat(1, 10).reshape(2,-1)
垂直堆叠？

In [48]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

如何将数组
a = np.arange(10).reshape(2,-1)
和数组
b = np.repeat(1, 10).reshape(2,-1)
水平堆叠？

In [49]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

如何获取数组
a = np.array([1,2,3,2,3,4,3,4,5,6])
和数组
b = np.array([7,2,10,2,7,4,9,4,9,8])
元素相匹配的位置？

In [52]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
location=np.where(a==b)
location

(array([1, 3, 5, 7], dtype=int64),)

 如何从数组
np.arange(15)
中提取5到10之间的所有数字？

In [57]:
a=np.arange(15)
a[(a>=5)&(a<=10)]

array([ 5,  6,  7,  8,  9, 10])

如何交换数组
np.arange(9).reshape(3,3)
中的第1列和第2列？

In [68]:
a=np.arange(9).reshape(3,3) 
# 先切分
a1=a[:,:1]
a2=a[:,1:2]
a3=a[:,2:3]
a4=np.concatenate([a2,a1,a3],axis=1)
print(a4)

# 方法2  意思是在列的维度上 之前是0,1,2 现在换成了 1,0,2
a[:,[1,0,2]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

如何创建一个形状为5x3的二维数组，其包含5到10之间的随机浮点数？

In [70]:
np.random.rand(5,3)+np.random.randint(5,11,size=(5,3))

array([[ 9.92529062,  6.46242094,  8.32940533],
       [ 5.06946617, 10.29476187,  5.01008494],
       [10.72679123,  7.4123887 ,  8.96556407],
       [ 6.75836927, 10.57071364,  8.80993781],
       [ 9.32947714,  6.16068677,  8.17099685]])

如何获取数组
a = np.array([1,2,3,2,3,4,3,4,5,6])
和数组
b = np.array([7,2,10,2,7,4,9,4,9,8])
之间的共同元素？

In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
# 这一步得出的结果时 true false的数组
index=np.isin(a,b)
# 直接这样操作就可以得到true的元素
a[index]
# unique 是去重
c=np.unique(a[index])


# 方法2 
d=np.intersect1d(a,b)
print(c,d)

[2 4] [2 4]


如何从数组
a = np.array([1,2,3,2,3,4,3,4,5,6])
中删除在数组
b = np.array([7,2,10,2,7,4,9,4,9,8])
中存在的所有元素？

In [83]:
index=np.isin(a,b)
# 直接 a[index]的话是取的存在的元素  不存在要加~ 类似于取反
a[~index]

array([1, 3, 3, 3, 5, 6])

如何反转二维数组

In [87]:
a=np.arange(9).reshape(3,3)
a[:,::-1]
a[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

如何把数组
np.arange(15)的
随机位换成值44？

In [115]:
array=np.arange(15)
np.random.seed(100)
array[np.random.choice(len(array))]=44
array
np.random.choice(10)

8

 如何查找数组
np.array([1,2,3,2,3,4,3,4,5,6])
中的唯一值的数量？

In [134]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.unique(a,return_counts=True)
b
# c=np.where(b==1)
# c.size

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1], dtype=int64))

如何找到二维数组
np.arange(9).reshape(3,3)
每一行中的最大值？

In [136]:
a=np.arange(9).reshape(3,3)
np.max(a,axis=1)

array([2, 5, 8])

给出起点2，长度10和步长3，如何创建一个numpy数组？

In [137]:
array=np.arange(2,3*10+2,3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

 如何从二维数组a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])中的每行减去一维数组b_1d = np.array([1,2,3])中相应的值？

In [139]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
c=b_1d[:,np.newaxis]
a_2d-c

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

如何知道数组
np.array([1,2,3,2,3,4,3,4,5,6])
有没有NaN值？

In [141]:
a=np.array([1,2,3,2,3,4,3,4,5,6]) 
a.all()

False

如何把数组中的NaN值替换成0？

In [144]:
array=np.array([1,2,3,2,np.nan,4,3,4,5,6])
array[np.isnan(array)]=0
array

array([1., 2., 3., 2., 0., 4., 3., 4., 5., 6.])

如何知道数组
np.array([7,2,10,2,7,4,9,4,9,8])
中的第二大值是多少？

In [155]:
# np.unique 不仅去重还进行了从小到大的排序
a=np.array([7,2,10,2,7,4,9,4,9,8,10]) 
np.unique(a)

9

29. 如何把数组
np.random.randint(1,10(3,3))
按照数组最后一列的数值进行排序？

In [182]:
np.random.seed(4)
array=np.random.randint(1,10,(3,3))
# argsort 是返回数组排序个位置的序号
a=np.argsort(array[:,-1])
array[a,:]

array([[8, 6, 2],
       [3, 8, 8],
       [9, 8, 9]])

如何知道数组
np.array([7,2,10,2,7,2,4,9,4,9,8])
中出现频率最高的值是什么？

In [188]:
array=np.array([7,2,10,2,7,2,4,9,4,9,8])
most_frequent=np.unique(array,return_counts=True)[0][0]
most_frequent

2

如何找出数组np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])中第五个1出现的位置？

In [190]:
array=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.argsort(array)

array([ 0,  2,  3,  7,  8, 10, 11,  1,  9, 12,  4,  6,  5], dtype=int64)